# -*- coding: utf-8 -*-
"""Pizza Order System .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N204H7RHLbfUuDwmYiBpi90qgJ0Xex92
"""

#kitaplık içe aktarma
import csv 
import datetime

#menu dosyası olusturma
menu_file = open('menu.txt', "w")

menu_file.write('* Menu:' 
'1: Klasik Pizza'                
'2: Margarita Pizza'
'3: Turk Pizza'
'4: Sade Pizza' 
'* decorator :' 
'5: Olive'
'6: Mushroom'
'7: Goat Cheese' 
'8: Meat'
'9: Onion' 
'10: Corn'
'* Teşekkür ederiz!')
menu_file.close()

#pizza üst sınıfı oluşturma 
class Pizza:
 def __init__(self, description, cost):
  self.__description = description 
  self.__cost = cost

 def get_description(self):
   return self.__description

 def get_cost(self):
   return self.__cost

from os import confstr_names
#pizza alt sınıfları oluşturma
class Pizza:
 def __init__(self, name, cost, ingredients):
   self.__name = name
   self.__cost = cost
   self.__ingredients = ingredients 

 def get_name(self):
  return self.__name 

 def get_cost(self):
  return self.__cost

 def get_ingredients(self):
   return self.__ingredients

class KlasikPizza(Pizza):
  def __init__(self):
     name = "Klasik Pizza"
     cost = 50 
     ingredients = ["tomato sauce", "cheese", "pepper", "tomato"]
     super().__init__(name, cost, ingredients)

  
class MargaritaPizza(Pizza):
  def __init__(self):
      name = "Margarita Pizza"
      cost = 40
      ingredients = ["tomato sauce", "cheese", "tomato", "basil"]
      super().__init__(name, cost, ingredients)
    

class TurkPizza(Pizza):
  def __init__(self):
      name = "Turk Pizza"
      cost = 80 
      ingredients = ["tomato sauce", "cheese", "sucuk"]
      super().__init__(name, cost, ingredients)


class SadePizza(Pizza):
  def __init__(self):
    name = "Sade Pizza"
    cost= 30
    ingredients = ["tomato sauce", "cheese"]
    super().__init__(name, cost, ingredients)

#decorator sınıfı oluşturma 
class Decorator(Pizza):
    def __init__(self,pizza):
        self.__pizza = pizza

    def get_description(self):
      return self.__pizza.get_description()
    def get_cost(self):
      return self.__pizza.get_cost() + self.__price()


class Olive(Decorator):
   def __init__(self, pizza):
      super().__init__(pizza)
      self.__name = "Olive"
      self.__price = 5 

   def get_description(self):
       return self.__pizza.get_description + "," + self.__name

   def get_cost(self):
       return self.__price


class Mushroom(Decorator):
  def __init__(self, pizza):
      super().__init__(pizza)
      self.__name = "Mushroom"
      self.__price = 10 

  def get_description(self):
      return self.__pizza.get_description + "," + self.__name

  def get_cost(self):
      return self.__price


class GoatCheese(Decorator):
  def __init__(self, pizza):
      super().__init__(pizza)
      self.__name = "Goat Cheese"
      self.__price = 20

  def get_description(self):
      return self.__pizza.get_description + "," + self.__name

  def get_cost(self):
      return self.__price


class Meat(Decorator):
  def __init__(self, pizza):
      super().__init__(pizza)
      self.__name = "Meat"
      self.__price = 25
    
  def get_description(self):
      return self.__pizza.get_description + "," + self.__name
 
  def get_cost(self):
      return self.__price
 

class Onion(Decorator):
  def __init__(self, pizza):
      super().__init__(pizza)
      self.__name = "Onion"
      self.__price = 5

  def get_description(self):
      return self.__pizza.get_description + "," + self.__name

  def get_cost(self):
      return self.__price

class Corn(Decorator):
  def __init__(self, pizza):
      super().__init__(pizza)
      self.__name = "Corn"
      self.__price = 5

  def get_description(self):
      return self.__pizza.get_description + "," + self.__name

  def get_cost(self):
      return self.__price

#main fonksiyon oluşturup menuyü ekrana yazdırıp, pizza ve sos seçimi ve toplam tutar işlemleri yapma
def main():
    print("Menu:")
    print("1.Klasik Pizza")
    print("2.Margarita Pizza")
    print("3.Turk Pizza")
    print("4.Sade Pizza")

    pizza_choice = int(input("Choose pizza from the menu (1-4):"))
    if pizza_choice == 1:
       pizza = KlasikPizza()
    elif pizza_choice == 2:
       pizza = MargaritaPizza()
    elif pizza_choice == 3:
       pizza = TurkPizza()
    elif pizza_choice == 4:
       pizza = SadePizza()
    else:
      print("Invalid choice, please try again ")
      return
    
    ingredients = pizza.get_ingredients()
    print("Ingredients of the chosen pizza:")
    print(ingredients)


    print("Decorator:")
    print("5.Olive")
    print("6.Mushroom")
    print("7.Goat Cheese")
    print("8.Meat")
    print("9.Onion")
    print("10.Corn")

    decorator_choice = int(input("Choose decorator (5-10):"))
    if decorator_choice == 5:
       decorator = Olive(pizza)
    elif decorator_choice == 6:
       decorator = Mushroom(pizza)
    elif decorator_choice == 7:
       decorator = GoatCheese(pizza)
    elif decorator_choice == 8:
       decorator = Meat(pizza)
    elif decorator_choice == 9:
       decorator = Onion(pizza)
    elif decorator_choice == 10:
       decorator = Corn(pizza)
    else:
      print("Invalid choice, please choose decorator")

    total_cost = pizza.get_cost()
    decorator_cost = decorator.get_cost()
    print("Total cost:")
    total = total_cost + decorator_cost
    print( str(total) + "TL")
    

    name = input("Please enter your full name:")
    tc_number = input("Please enter your TC number:")
    credit_card_number = input("Please enter your card number:")
    credit_card_password = input("Please enter your card password:")

    print("Thanks for your order. Bon appétit!")

#bilgileri veritabanına kaydetme 
    import csv 
    
    def save_order_to_database(order):
        with open("Orders_database.csv", mode = "a", newline ="") as database:
          writer = csv.writer(database)
          writer.writerow(order)
main()